/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Card(props) {
  const { nodes, materials } = useGLTF("/credit_card_white/card.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[20.3, -9.5, 0]} scale={1.9} position={[0, -1.9, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[0, 102.05, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Credit_Card_Credit_Card_Material_0.geometry}
              material={materials.Credit_Card_Material}
              scale={1.52}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/credit_card_white/card.glb");
